FROM python:3.13-alpine
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
RUN apk add --no-cache ca-certificates poppler-utils
RUN addgroup -S app && adduser -S app -G app
WORKDIR /app
COPY extractor/app.py /app/app.py
RUN chown -R app:app /app
USER app
EXPOSE 9090
CMD ["python3","/app/app.py"]
